apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: cm
    envs:
      - ./service.env

namePrefix: spring-config-

commonLabels:
  appsvc: spring-config