apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  selector:
    appsvc: svc # will be replaced by kustomization

  type: ClusterIP
  ports:
  - name: app
    protocol: TCP
    port: 80 
    targetPort: app-port