apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - name: app-cm
    envs:
      - app.env

patches:
  - target:
      kind: Deployment
    # Example of the patching the field that cannot be done via strategic merge
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/envFrom/-
        value:
          configMapRef:
              name: app-cm